---
- name: fetch logs from remote host
  hosts: all
  vars:
    - ansible_python_interpreter: "/usr/bin/python3.8"
  tasks:
    - set_fact:
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
      delegate_to: localhost
      delegate_facts: true
    - name: fetch logs
      debugger: on_failed
      cisco.ios.ios_command:
        commands:
          - show logging
